repository:
  has_wiki: false
  has_discussion: true
  default_branch: main

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
