---
name: 🐛 Bug Report
description: Something isn't working as expected
labels:
  - bug
body:
  - type: input
    id: testcase
    attributes:
      label: Reproducible test case
      description:
        If possible, please create a minimal test case that reproduces your
        problem.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Additional information
      description:
        Please share any other relevant information not mentioned above. What
        did you expect to happen? What do you think the problem might be?
