import React from 'react'
import CardGrid from '@/components/molecules/CardGrid'

const cards = [
  {
    title: 'Github Setter',
    subtitle: 'Repo manager',
    url: 'https://github.com/seonglae/github-setter',
    icon: 'icon/npm.png',
    background: '#fff',
    color: 'black',
    ratio: '200%',
  },
  {
    title: 'Dancing Button',
    subtitle: 'native liquid btn',
    url: 'https://github.com/seonglae/dancing-button',
    icon: 'icon/npm.png',
    background: '#fff',
    color: 'black',
    ratio: '200%',
  },
  {
    title: 'To Smooth',
    subtitle: 'chaikin algorithm',
    url: 'https://github.com/seonglae/to-smooth',
    icon: 'icon/npm.png',
    background: '#fff',
    color: 'black',
    ratio: '200%',
  },
  {
    title: 'VSCode Intuiter',
    subtitle: 'Extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.intuiter-vscode',
    icon: 'icon/vscode.png',
    background: '#232730',
    color: 'white',
    ratio: '50%',
  },
  {
    title: 'Terminal Intuiter',
    subtitle: 'Extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.terminal-intuiter',
    icon: 'icon/vscode.png',
    background: '#232730',
    color: 'white',
    ratio: '50%',
  },
  {
    title: 'Work Intuiter',
    subtitle: 'Extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.workspace-intuiter',
    icon: 'icon/vscode.png',
    background: '#232730',
    color: 'white',
    ratio: '50%',
  },
  {
    title: 'Git Intuiter',
    subtitle: 'Extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.git-intuiter',
    icon: 'icon/vscode.png',
    background: '#232730',
    color: 'white',
    ratio: '50%',
  },
  {
    title: 'One Dark Teal',
    subtitle: 'VSCode theme',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.one-dark-teal',
    icon: 'icon/vscode.png',
    background: '#232730',
    color: 'white',
    ratio: '50%',
  },
  {
    title: 'CStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.cstack',
    icon: 'https://github.com/seonglae/cstack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'EStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.estack',
    icon: 'https://github.com/seonglae/estack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'PStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.pstack',
    icon: 'https://github.com/seonglae/pstack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'TStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.tstack',
    icon: 'https://github.com/seonglae/tstack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'WStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.wstack',
    icon: 'https://github.com/seonglae/wstack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'VStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.vstack',
    icon: 'https://github.com/seonglae/vstack/raw/HEAD/images/vstack.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'GStack',
    subtitle: 'VSCode extension group',
    url: 'https://marketplace.visualstudio.com/items?itemName=seonglae.gstack',
    icon: 'https://github.com/seonglae/gstack/raw/HEAD/images/logo.png',
    background: '#425052',
    color: 'white',
    ratio: '75%',
  },
  {
    title: 'Nextra',
    subtitle: 'Template web app',
    url: 'https://github.com/seonglae/nextra',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
  {
    title: 'Nuxtify',
    subtitle: 'Template web app',
    url: 'https://github.com/seonglae/nextify',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
  {
    title: 'WDpress',
    subtitle: 'Template web app',
    url: 'https://github.com/seonglae/windipress',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
  {
    title: 'reacterial',
    subtitle: 'Template web app',
    url: 'https://github.com/seonglae/reacterial',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
  {
    title: 'Basher',
    subtitle: 'Template repo',
    url: 'https://github.com/seonglae/basher',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
  {
    title: 'tsmodule',
    subtitle: 'Template repo',
    url: 'https://github.com/seonglae/ts-module',
    icon: 'icon/github-white.png',
    background: '#424242',
    color: '#000',
    ratio: '50%',
  },
]

export const Others: React.FC = () => {
  return <CardGrid cards={cards} small />
}
